cache:
  pipeline: [~/.npm]

shared:
  image: node:12

jobs:
  main:
    annotations:
      screwdriver.cd/ram: TURBO
      screwdriver.cd/cpu: TURBO
    steps:
      - install-chrome: ./build-scripts/setup-chrome.sh
      - install: npm ci
      - test-navi-admin: npx lerna run test --scope navi-admin --stream;
      - test-navi-app: npx lerna run test --scope navi-app --stream;
      - test-navi-core: npx lerna run test --scope navi-core --stream;
      - test-navi-dashboards: npx lerna run test --scope navi-dashboards --stream;
      - test-navi-data: npx lerna run test --scope navi-data --stream;
      - test-navi-directory: npx lerna run test --scope navi-directory --stream;
      - test-navi-notifications: npx lerna run test --scope navi-notifications --stream;
      - test-navi-reports: npx lerna run test --scope navi-reports --stream;
      - test-navi-search: npx lerna run test --scope navi-search --stream;
      - test-navi-webservice: cd packages/webservice && ./gradlew assemble && cd -;
    requires:
      - ~pr
      - ~commit
