cache:
  pipeline:
    - ~/.npm,
    - ~/.gradle,
    - $SD_SOURCE_DIR/node_modules
    - $SD_SOURCE_DIR/packages/admin/node_modules
    - $SD_SOURCE_DIR/packages/app/node_modules
    - $SD_SOURCE_DIR/packages/core/node_modules
    - $SD_SOURCE_DIR/packages/dashboards/node_modules
    - $SD_SOURCE_DIR/packages/data/node_modules
    - $SD_SOURCE_DIR/packages/directory/node_modules
    - $SD_SOURCE_DIR/packages/notifications/node_modules
    - $SD_SOURCE_DIR/packages/reports/node_modules
    - $SD_SOURCE_DIR/packages/search/node_modules
    - $SD_SOURCE_DIR/packages/webservice/node_modules

shared:
  annotations:
    steps:
      - .: &install-node
          install-node: |
            sd-cmd exec screwdriver/install-nodejs@latest $NODE_VERSION
            export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" && nvm use node
      - .: &npm-ci
          npm-ci: npm ci --unsafe-perm
      - .: &install-chrome
          install-chrome: ./build-scripts/setup-chrome.sh
    jobs:
      main-npm-test-job: &main-npm-test-job
        image: timbru31/node-chrome:14
        annotations:
          screwdriver.cd/ram: HIGH
          screwdriver.cd/cpu: HIGH
        steps:
          - *npm-ci
          - test-package: npx lerna run test --scope $PACKAGE --stream;
        requires:
          - ~pr
          - ~commit
        environment:
          JOBS: 1
  environment:
    NODE_VERSION: 14.16.1
    HUSKY_SKIP_INSTALL: true
    JOBS: 1

jobs:
  lint:
    <<: *main-npm-test-job
    annotations:
      screwdriver.cd/ram: LOW
      screwdriver.cd/cpu: LOW
    steps:
      - *npm-ci
      # TODO add lint meta https://docs.screwdriver.cd/user-guide/metadata#additional-pull-request-checks
      - lint-pretty: npx prettier -c --config prettier.config.js packages/*/{addon,tests}/**/*.{js,ts};
      - lint-styles: npx stylelint "**/*.scss";
      - lint-addons: npx lerna run lint --stream;
  main-admin:
    <<: *main-npm-test-job
    annotations:
      screwdriver.cd/ram: LOW
    environment:
      PACKAGE: navi-admin
  main-app:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-app
  main-core:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-core
  main-dashboards:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-dashboards
  main-data:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-data
  main-directory:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-directory
  main-notifications:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-notifications
  main-reports:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-reports
  main-search:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-search
  main-webservice:
    image: openjdk:11-jdk
    steps:
      - *install-node
      - *npm-ci
      - test-navi-webservice: cd packages/webservice && ./gradlew check && cd -;
    requires:
      - ~pr
      - ~commit
    environment:
      JOBS: 1
  main:
    image: screwdrivercd/noop-container
    annotations:
      screwdriver.cd/ram: MICRO
      screwdriver.cd/cpu: MICRO
    steps:
      - success: echo "success"
    requires:
      [
        lint,
        main-admin,
        main-app,
        main-core,
        main-dashboards,
        main-data,
        main-directory,
        main-notifications,
        main-reports,
        main-search,
        main-webservice,
      ]

  alpha-main:
    image: maven:3.6.3-jdk-8
    annotations:
      screwdriver.cd/ram: TURBO
      screwdriver.cd/cpu: TURBO
    steps:
      - *install-node
      - *npm-ci
      - *install-chrome
      - test-navi-admin: npx lerna run test --scope navi-admin --stream;
      - test-navi-app: npx lerna run test --scope navi-app --stream;
      - test-navi-core: npx lerna run test --scope navi-core --stream;
      - test-navi-dashboards: npx lerna run test --scope navi-dashboards --stream;
      - test-navi-data: npx lerna run test --scope navi-data --stream;
      - test-navi-directory: npx lerna run test --scope navi-directory --stream;
      - test-navi-notifications: npx lerna run test --scope navi-notifications --stream;
      - test-navi-reports: npx lerna run test --scope navi-reports --stream;
      - test-navi-search: npx lerna run test --scope navi-search --stream;
      - test-navi-webservice: cd packages/webservice && ./gradlew check && cd -;
    requires:
      - ~commit:0.2.x-alpha
      - ~pr:0.2.x-alpha

  publish-npm:
    image: node:14.16.1
    annotations:
      screwdriver.cd/ram: LOW
      screwdriver.cd/cpu: LOW
    requires:
      - ~main
      - ~alpha-main
    environment:
      GIT_SHALLOW_CLONE: false
    steps:
      - *npm-ci
      - publish: ./scripts/npm-publish.sh
    secrets:
      - NPM_TOKEN

  publish-artifactory:
    image: maven:3.6.3-jdk-8
    annotations:
      screwdriver.cd/ram: LOW
      screwdriver.cd/cpu: LOW
    requires:
      - ~main
      - ~alpha-main
    steps:
      - publish: ./scripts/artifactory-publish.sh
    secrets:
      - ARTIFACTORY_USER
      - ARTIFACTORY_KEY

  gh-pages:
    image: node:14.16.1
    requires: main
    environment:
      BUILD_NAVI_DEMO: true
    steps:
      - *npm-ci
      - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git /tmp/ci
      - build-pages: |
          cd packages/app
          npx ember github-pages:commit --message "Deploy gh-pages from $SD_BUILD_SHA" --destination ../../
      - deploy: |
          . /tmp/ci/git-ssh.sh
          git push origin gh-pages:gh-pages
    secrets:
      - GIT_KEY_BASE64
